/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sushantdotel.graphs;

public class App {
    public String getGreeting() {
        return "Hello java my old friend";
    }

    public static void main(String[] args) {

        Graph g1 = new Graph(7);
        g1.adj(1);
        g1.addEdge(1, 2);
        g1.addEdge(3, 6);
        for (int v : g1.adj(1)) {
            System.out.println(v);
        }
        for (int v : g1.adj(2)) {
            System.out.println(v);
        }
    }
}
